
server:
  port: 6262

log:
  dir: node-client-logs
  name: node-client

mqtt:
  host: ${MQTT_HOST}
  port: ${MQTT_PORT}
  username: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  server-id: ${SERVER_ID}
