
log:
  dir: node-server-logs
  name: node-server

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWPRD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}


mqtt:
  host: ${MQTT_HOST}
  port: ${MQTT_PORT}
  username: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}
  server-id: ${SERVER_ID}

